[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
gl = "0.14.0"
image = "0.25.6"
nalgebra = "0.33.2"
sdl2 = "0.37.0"
tobj = "4.0.3"
vertex_attrib = {path = "vertex_attrib"}
